- hosts: RHEL
  # roles:
  #   - azurefile-download

  tasks:
  # - set_fact:
  #     mount: "{{ ansible_mounts | first }}"
                                                                                                                          
  # - set_fact: 
  #     disk_available: "{{ (mount.size_available / 1000000000) | round(1, 'common') }}"
 

  # - name: Check if there is enough space
  #   assert:
  #     that: disk_available|int  > 3

  # - set_fact: disk_available ="{{ (mount.size_available / 1000000000) | round(1, 'common') }}GB"


  - name: "Check available storage space (RHEL)"
    when:
      - ansible_facts['os_family'] == "RedHat"
    block:
      - set_fact:
          mount: "{{ ansible_mounts | first }}"
                                                                                                                              
      - set_fact: 
          disk_available_gb: "{{ (mount.size_available / 1000000000) | round(1, 'common') }}"

      - name: Check if there is enough space
        assert:
          that: disk_available_gb|int  > 3
