- hosts: Windows

  tasks:
  - name: Check sensor version
    ansible.windows.win_command:
      argv:
      - C:\Program Files\CrowdStrike\CSSensorSettings.exe
      - --version
    register: result

  - name: Print CSSensor information
    ansible.builtin.debug:
      var: result.stdout_lines[0]

  - name: extract CSSensor version
    set_fact:
      cssensor_version: "{{ result.stdout_lines[0]|replace('CsSensorSettings Version:', '')|trim }}"

  - name: Print CSSensor version
    ansible.builtin.debug:
      var: cssensor_version

  - name: Check CSSensor version
    assert:
      that: cssensor_version  > '7.04.17604.0'
