# defaults for falcon_uninstall

# Additional arugments to uninstall the sensor.
# You can add your maintenance token here by adding MAINTENANCE_TOKEN=<token>
#
falcon_windows_uninstall_args: "/norestart"

# Ansible become method for Windows systems.
# The default is runas
#
falcon_windows_become_method: runas

# Ansible become user for Windows systems.
# The default is SYSTEM
#
falcon_windows_become_user: SYSTEM

smb_sourcepath: '//testaabc.file.core.windows.net/agents'

smb_username:

smb_password:

smb_targetpath: '/mnt/smb_share'


storageAccountName: "testaabc"
storageAccountKey: "xgWHf1BM5v+Kbj88pg7pR/bfoTBHjmIgUOsU4NiD8HE0dfL8RTdjxToe1XxaK9r7BNAb5z+EWwzP+AStCRMUUg=="
containerName: "testabc"
blobName: "dd-qed-qede-qedf-qedi-qedr-8.33.0.20_dup7.6-1.el7_6.iso"
destinationPath: "c:\temp"
