---
# Windows block
- name: "Check available storage space (Windows)"
  when:
    - ansible_facts['os_family'] == "Windows"
  block:
    - name: Check sensor version
      win_shell: "C:\Program Files\CrowdStrike\CSSensorSettings.exe" --version
      register: cssensor_version

    # - name: Check storage size 1GB or above available space
    #   assert:
    #     that: disk_available_gb|int  > 1

# Linux Block
# - name: "Check available storage space (RHEL)"
#   when:
#     - ansible_facts['os_family'] == "RedHat"
#   block:
#     - set_fact:
#         mount: "{{ ansible_mounts | first }}"
                                                        

# - name: show sql server version
#   debug:
#     msg: "SQL server: {{ sql_server_edition }} - {{ sql_server_version }} - {{ sql_server_patchlevel }}"