---
- name: CrowdStrike Falcon | Install Falcon Sensor Package (Linux)
  ansible.builtin.dnf:
    name: "{{ falcon_sensor_pkg }}"
    disable_gpg_check: true
    state: present

- name: CrowdStrike Falcon | Gather tmp install directory objects
  ansible.builtin.find:
    paths: "{{ falcon_install_tmp_dir }}"
    patterns: "ansible.*falcon"
    file_type: directory
  register: falcon_tmp_dir_objects
  when: falcon_install_tmp_dir | length > 0
  changed_when: no

- name: CrowdStrike Falcon | Remove tmp install directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ falcon_tmp_dir_objects.files }}"
  when:
    - falcon_install_tmp_dir | length > 0
    - falcon_tmp_dir_objects is defined and falcon_tmp_dir_objects.files | length > 0
  changed_when: no

- name: CrowdStrike Falcon | Remove Falcon Sensor Package (local file)
  ansible.builtin.file:
    path: "{{ falcon_localfile_path }}"
    state: absent
  changed_when: no

- name: CrowdStrike Falcon | Install Falcon Sensor
  ansible.builtin.command: "/opt/CrowdStrike/falconctl -s --cid={{ falcon_cid }} -f"
  become: true
  register: result
