---
# tasks file for falcon_install
- name: Preinstall block
  block:
    - ansible.builtin.include_tasks: preinstall.yml

- name: CrowdStrike Falcon | Set full file path
  ansible.builtin.set_fact:
    falcon_sensor_pkg: "{{ falcon_localfile_path }}"
  when:
    - falcon_localfile_path | length > 0

- name: Install block (linux)
  when:
    - ansible_facts['os_family'] != "Windows"
  become: true
  become_user: root
  block:
    - ansible.builtin.include_tasks: install.yml

- name: Install block (windows)
  when:
    - ansible_facts['os_family'] == "Windows"
  become: true
  become_method: "{{ falcon_windows_become_method }}"
  become_user: "{{ falcon_windows_become_user }}"
  block:
    - ansible.builtin.include_tasks: win_install.yml