---
- name: "CrowdStrike Falcon | Default Operating System configuration"
  ansible.builtin.set_fact:
    falcon_target_os: "{{ ansible_facts['distribution'] }}"
    falcon_os_family: "{{ ansible_facts['system'] | lower }}"
    falcon_os_version: "*{{ ansible_facts['distribution_major_version'] }}*"
    falcon_sensor_update_policy_platform: "{{ ansible_facts['system'] }}"
    falcon_os_vendor: "{{ ansible_facts['os_family'] | lower if (ansible_facts['os_family'] == 'RedHat') else ansible_facts['distribution'] | lower }}"

- name: "CrowdStrike Falcon | Determine if Endpoint Operating System Is RHEL"
  ansible.builtin.set_fact:
    falcon_target_os: "*RHEL*"
  when: ansible_facts['os_family'] == "RedHat"

- name: "CrowdStrike Falcon | Endpoint Operating System Detected Is Microsoft Windows"
  ansible.builtin.set_fact:
    falcon_os_version: ""
    falcon_target_os: "Windows"
    falcon_sensor_update_policy_platform: "{{ ansible_facts['os_family'] }}"
  when: ansible_facts['os_family'] == "Windows"

- name: CrowdStrike Falcon | Verify Temporary Install Directory Exists (Linux)
  ansible.builtin.tempfile:
    path: "{{ falcon_install_tmp_dir }}"
    state: directory
    suffix: falcon
  when:
    - ansible_facts['system'] == "Linux"
    - falcon_install_tmp_dir is defined
  register: falcon_install_temp_directory
  changed_when: no

- name: CrowdStrike Falcon | Verify Temporary Install Directory Exists (Windows)
  ansible.windows.win_tempfile:
    path: "{{ falcon_windows_tmp_dir }}"
    state: directory
    suffix: falcon
  when:
    - ansible_facts['os_family'] == "Windows"
    - falcon_windows_tmp_dir is defined
  register: falcon_install_win_temp_directory
  changed_when: no

- name: "CrowdStrike Falcon | Override falcon_sensor_version_decrement when falcon_sensor_update_policy_name or falcon_sensor_version set"
  ansible.builtin.set_fact:
    falcon_sensor_version_decrement: 0
  when:
    - falcon_sensor_update_policy_name or
      falcon_sensor_version

- name: CrowdStrike Falcon | Override falcon_sensor_version when set
  ansible.builtin.set_fact:
    falcon_sensor_version: "+version:'{{ falcon_sensor_version }}'"
  when: falcon_sensor_version | length > 0

