---
# - name: Install cifs-utils
#   ansible.builtin.dnf:
#     name: cifs-utils
#     state: present
#   become: true
#   delegate_to: localhost

- name: Create mount point directory if it does not exist
  ansible.builtin.file:
    path: "{{ smb_targetpath }}"
    state: directory
    mode: '0755'
  become: true
  delegate_to: localhost

- name: Create credential directory if it does not exist
  ansible.builtin.file:
    path: /etc/smbcredentials
    state: directory
    mode: '0755'
  become: true
  delegate_to: localhost

- name: Create credential username
  ansible.builtin.shell: bash -c 'echo "username={{ smb_username }}" >> /etc/smbcredentials/{{ smb_username }}.cred'
  become: true
  delegate_to: localhost

- name: Create credential password
  ansible.builtin.shell: bash -c 'echo "password={{ smb_password }}" >> /etc/smbcredentials/{{ smb_username }}.cred'
  become: true
  delegate_to: localhost

- name: Unmount a mounted volume
  ansible.posix.mount:
    path: "{{ smb_targetpath }}"
    state: unmounted
  become: true
  delegate_to: localhost
  ignore_errors: true

- name: check if 20.47.17.105:455 is accessible
  wait_for:
    host: 20.47.17.105
    port: 445
    state: started
    delay: 0
    timeout: 1

# - name: Mount ephemeral SMB volume
#   ansible.posix.mount:
#     src: "{{ smb_sourcepath }}"
#     path: "{{ smb_targetpath }}"
#     opts: "rw,serverino,nosharesock,actimeo=30,file_mode=0777,dir_mode=0777,credentials=/etc/smbcredentials/{{ smb_username }}.cred,context=system_u:object_r:container_file_t:s0"
#     fstype: cifs
#     state: ephemeral
#   become: true
#   delegate_to: localhost


- name: Mount ephemeral SMB volume
  ansible.builtin.shell: mount -t cifs //testaabc.file.core.windows.net/agents /mnt/agents -o credentials=/etc/smbcredentials/testaabc.cred,dir_mode=0777,file_mode=0777,serverino,nosharesock,actimeo=30,context=system_u:object_r:container_file_t:s0
  become: true
  delegate_to: localhost
