---
- name: Add a PowerShell module
  community.windows.win_psmodule:
    name: az.storage
    state: present

- name: Run a pwsh command
  shell: "New-AzStorageContext -StorageAccountName {{ storageAccountName }} -StorageAccountKey {{ storageAccountKey }}"
  # args:
  #   executable: /usr/bin/pwsh
  register: result

- name: context result
  debug:
    msg: "{{ result }}"

- name: Run a pwsh command
  shell: "get-AzStorageBlobContent -Container {{ containerName }} -Blob {{ blobName }} -Destination {{ destinationPath }} -Context {{ context }} -Force"
  # args:
  #   executable: /usr/bin/pwsh
  register: result2
